version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  gulp:
    image: node:8
    user: root
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: "npm run start"      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql    
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: somewordpress    
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql   
    volumes:
      - ./phpunit.xml:/var/www/html/phpunit.xml    
      - ./tests:/var/www/html/tests     
      - ./vendor:/var/www/html/vendor
      - ./src/plugins:/var/www/html/wp-content/plugins
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"
  composer:
    image: composer:1.9.3
    volumes:
      - .:/app
    command: install   